# Generated by Django 5.0.4 on 2024-04-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="con_password",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="person",
            name="password",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone_no",
            field=models.IntegerField(),
        ),
    ]
